### ISSUE TITLE
Is there a program or tutorial to decode the nfc tag data or msd data?

### ISSUE THREAD

**Issue by Pdubs19** [ElectronicCats/NFC-Copy-Cat#4]
Is there any tutorials of sites with more info on decrypting nfc data and converting it to magstripe data. My main question is why is Magstripe data so important? How did Samy Kamkar figure out what parts of track 2 discretionary data needed to be changed in order to downgrade the service code from 201 to 101. Was his downgrade method simply using his algorithim to use a previous cards CVC3 or CVV2 on the magstripe and apply it to the new card?

**Comment by Pdubs19** [comment]
Any suggestions for the best programs to use for going through the nfc data while using arduino? Rn I've been using arduino's serial monitor or putty connected to the serial port.

**Comment by Pdubs19** [comment]
Any ideas on the best software to use for decrypting the nfc data on windows 10. Also I've successfully uploaded the read replay spoof code and was able to send the nfc commands and get the responses as well as find track 2. Although when I disconnect the nfc cat from power I have to re read the nfc tag all over again. Does this device not save the info in order to spoof nfc and magspoof once the power is disconnected.

**Comment by salmg** [comment]
Hello @Pdubs19 

Answering your questions:
1. "is why is Magstripe data so important?" - Because it what the payment systems implements to charge amount to an account. The mag-stripe contains all the necessary data to do that, such as, PAN, expiration date, service code, discretionary data...

2. "How did Samy Kamkar figure out what parts of track 2 discretionary data needed to be changed in order to downgrade the service code from 201 to 101." - It is a legacy compatibility in the payment systems to be able to do different payments without denying most of the transactions & because Samy is so smart. 

3. "Was his downgrade method simply using his algorithim to use a previous cards CVC3 or CVV2 on the magstripe and apply it to the new card?" - This replay attack only works in the Visa cards CVV mag-stripe data, as I mentioned before it works because compatibility.

4. "Does this device not save the info in order to spoof nfc and magspoof once the power is disconnected." - No, the device will not save the data that read afterwards. It will only save the track you assigned in the code.

To decode EMV, you can read the books in NFC Forum: https://www.emvco.com/emv-technologies/contact/

An online service that helps to decode EMV data automatically: https://emvlab.org/tlvutils/
